"""split_warranty_column

Revision ID: 5114191c61e2
Revises: 20260504aaaa
Create Date: 2026-05-08 03:59:06.253403

Splits quotation_items.warranty (VARCHAR free text) into:
  - warranty_count INT NULL
  - warranty_unit  ENUM('week','month') NULL

Backfills new columns from the legacy `warranty` strings, logs unparseable
rows to backend/migration_logs/<rev>_split_warranty_column.log, then drops
the old column.

Manual verification recipe:
  1. Take a copy of the dev DB (or a recent prod backup to a scratch DB).
  2. `alembic upgrade head`
  3. Spot-check: new columns exist, old `warranty` column gone, parsed
     values look correct on a sample, log file lists unparsed entries.
  4. `alembic downgrade -1`
  5. Spot-check: `warranty` column reconstructed, new columns gone.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.quotation.warranty_parser import parse_warranty


# revision identifiers, used by Alembic.
revision: str = '5114191c61e2'
down_revision: Union[str, Sequence[str], None] = '20260504aaaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Resolve repo-root migration_logs/ from this file's path.
# This file: backend/alembic/versions/<rev>.py  ->  parents[2] = backend/
_LOG_DIR = Path(__file__).resolve().parents[2] / "migration_logs"
_LOG_PATH = _LOG_DIR / f"{revision}_split_warranty_column.log"


def upgrade() -> None:
    # 1. Add new columns (nullable so we can backfill without a default).
    op.add_column(
        "quotation_items",
        sa.Column("warranty_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "quotation_items",
        sa.Column(
            "warranty_unit",
            sa.Enum("week", "month", name="warrantyunit"),
            nullable=True,
        ),
    )

    # 2. Backfill new columns from old `warranty` string.
    bind = op.get_bind()
    rows = bind.execute(
        sa.text("SELECT id, warranty FROM quotation_items WHERE warranty IS NOT NULL")
    ).fetchall()

    _LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_lines: list[str] = []
    parsed = 0
    unparsed = 0

    for row in rows:
        item_id = row[0]
        raw = row[1]
        count, unit, reason = parse_warranty(raw)
        if reason is not None:
            log_lines.append(f"id={item_id} raw={raw!r} reason={reason}")
            unparsed += 1
            continue
        if count is None or unit is None:
            # Treat as expected-empty (parser returned no reason); skip.
            continue
        bind.execute(
            sa.text(
                "UPDATE quotation_items "
                "SET warranty_count = :c, warranty_unit = :u "
                "WHERE id = :id"
            ),
            {"c": count, "u": unit, "id": item_id},
        )
        parsed += 1

    if log_lines or unparsed:
        header = (
            f"# Generated by alembic revision {revision} "
            f"on {datetime.now(timezone.utc).isoformat()}\n"
            f"# Format: id=<quotation_item_id> raw=<repr> reason=<short>\n"
            f"# parsed={parsed} unparsed={unparsed}\n"
        )
        _LOG_PATH.write_text(header + "\n".join(log_lines) + "\n", encoding="utf-8")

    # 3. Drop the old column.
    op.drop_column("quotation_items", "warranty")


def downgrade() -> None:
    # Add the old column back.
    op.add_column(
        "quotation_items",
        sa.Column("warranty", sa.String(length=20), nullable=True),
    )

    # Reconstruct the old string from the new columns.
    # Format: month -> "{n}th", week -> "{n}tuan". NULL stays NULL.
    bind = op.get_bind()
    rows = bind.execute(
        sa.text(
            "SELECT id, warranty_count, warranty_unit FROM quotation_items "
            "WHERE warranty_count IS NOT NULL AND warranty_unit IS NOT NULL"
        )
    ).fetchall()

    for row in rows:
        item_id, count, unit = row[0], row[1], row[2]
        suffix = "th" if unit == "month" else "tuan"
        bind.execute(
            sa.text("UPDATE quotation_items SET warranty = :w WHERE id = :id"),
            {"w": f"{count}{suffix}", "id": item_id},
        )

    # Drop new columns. Drop ENUM type explicitly on PostgreSQL backends; on
    # MySQL the ENUM is inline to the column and goes away with drop_column.
    op.drop_column("quotation_items", "warranty_unit")
    op.drop_column("quotation_items", "warranty_count")

    if bind.dialect.name == "postgresql":
        sa.Enum(name="warrantyunit").drop(bind, checkfirst=True)
