"""add_returns_table

Revision ID: d5764bf1da78
Revises: a3b913814125
Create Date: 2026-03-13 16:19:23.706291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5764bf1da78'
down_revision: Union[str, Sequence[str], None] = 'a3b913814125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Enum('seller_fault', 'customer_fault', name='returnreason'), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('refund_percent', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('returns')
    # ### end Alembic commands ###
